### ISSUE TITLE
Page Speed insights

### ISSUE THREAD

**Issue by andreweick** [andreweick/aedc2#16]
Just for fun, I ran [this](http://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Feick.us&tab=mobile) --- Are there any easy fixes in there?

**Comment by joshuaogle** [comment]
It's funny you mention that, we just did a bunch of those improvements yesterday for http://brightbit.com and got ours up to 85/100 and 91/100 (there's sort of a weird CSS "optimization" I disagree with). Some of the stuff we did was specific to the server setup, but I don't think I see those on yours (which suggests your server is already doing them).

They're definitely easy and I can get those improvements copied over

**Comment by joshuaogle** [comment]
The speed improvements are in now. The browser extension doesn't give me a score, but the only thing left to do is the server compression which I believe yours was doing already. It should be very good now :+1:

**Comment by andreweick** [comment]
:+1:
