### ISSUE TITLE
java not installed

### ISSUE THREAD

**Issue by andreweick** [andreweick/aedc2#19]
When I have 

activate :minify_javascript, compressor: Closure::Compiler.new

in my config file, it seems to want to install java.  Is there a way to run the gem and get the functionality w/o installing java?

**Comment by joshuaogle** [comment]
I think Closure is always going to require Java, but there are other compilers.
Closure is what Google uses to grade against so that guaranteed it would pass, but let's try it with Middleman's default Uglifier.

**Comment by andreweick** [comment]
No problem -- I'll install java (I wasn't thinking clearly -- I thought java was a run time dependency, but since it is static, it is only build time dependency.
