### ISSUE TITLE
social media icons

### ISSUE THREAD

**Issue by andreweick** [andreweick/aedc2#20]
Add social media things -- small and tasteful (if possible)
If possible, only want to include them on a few posts (for soccer parents)

**Comment by joshuaogle** [comment]
(For my own notes, but feel free to confirm)

Add social links to the bottom of blog posts, triggered by something like "sharing: true" in the meta. Do we want anything other than Twitter/Facebook/Google+?

**Comment by andreweick** [comment]
Twitter/Facebook/G+ are all I know, but if there is other ones.

Make it as small as possible, I'm trying not to look like tech crunch or something.  And I don't care "how many other's have G+ it"

Oh, could you add an "email" this post?

**Comment by andreweick** [comment]
awesome
