### ISSUE TITLE
About screen photograph format on iPhone

### ISSUE THREAD

**Issue by andreweick** [andreweick/aedc2#27]
I think the photo on the "about" screen is being skewed at iPhone size?

![2014-02-19 at 09 50 08](https://f.cloud.github.com/assets/1289435/2218512/27a8c8ee-9a30-11e3-9fce-b76e5685e896.png)

**Comment by joshuaogle** [comment]
It's because it is adjusting for the width, but didn't have "height" set to "auto".

This is fixed in the Stories PR (#26), so we can mark this closed once that's merged.
