### ISSUE TITLE
Stories layout

### ISSUE THREAD

**Issue by joshuaogle** [andreweick/aedc2#3]
Add slideshow support using Juicebox

We'll need the Juicebox Pro code. There is also the question of how images get into the Slideshow and where it is used. I assumed it would be on post pages, but Andy asked about XML/JSON. My plan was to create Ruby and Liquid tags so you could just add in an array.

Something like:

```
{% slideshow [{"/images/image1.png", "Image 1 Title"}, { "/images/image2.png", "Image 2 Title"}] %}
```

Or simpler if I can think of a way to do it

**Comment by andreweick** [comment]
Hmmm -- this is a tough one.

What about some JSON file in the ~/data/ directory?  Better ~/data/slideshow/.

Spitballing here, but what about a JSON file that has Image, Title, and then the markup would refer to that file.  I'm thinking I could write an applescript to export from aperture into the right format.  

How do you think that might be?  Can middleman read in files from the DATA directory at build?

**Comment by andreweick** [comment]
I'm starting to rethink the need for this -- I'm glad you left it for last!  I'll close it and come up with better requirements.  I'm thinking more of a responsive template for pages [like this](https://michellejensen.exposure.so/where-water-flows-falls)?

**Comment by joshuaogle** [comment]
That template does look nice. It would depend a lot on what you have in the post, but we could always set a "layout" variable in the post meta to trigger it. Just a thought.

I was going to talk to Jonathan about how we might do the JSON data, but it would definitely have been tricky and I think there are probably easier ways to do it.

**Comment by andreweick** [comment]
[These](https://www.storehouse.co/stories/s2lf-think-wide)[^1] templates idea is really intriguing to me, but I can't get my mind around requirements for you to work on.

It seems they break down into a few primitives
1. Full width image
2. Full screen image
3. inline image (inline image(s) block)
4. Text
5. Quote
6. Cool-ish title screen with parallax

(I expect you see the HTML and think "it's easy to layout like that") 

I think the big concept I am struggling with (and have been for a while) is how to size the images.  You will say "whatever size you want" (which is the only correct answer), but what I think I'm looking for is "These are the relative sizes of images" for each use (like #3 above)

So can you think of a way to template a page with elements above (liquid tags?)[^2]

Sorry for the essay question :-)

[1]: Even bad photography looks good.
[2]: I don't think you've ever asked, but any of the things you can make as components and open source, I'm in favor of -- I want to support making things that are donated back to the community, if it makes sense.

**Comment by joshuaogle** [comment]
Yep, getting the slideshow to function and in fairly simple template tags will be the easy part I think. The trickier part here might be the design question of how to customize the slideshow to do all of these different things.

Were we wanting the full-screen images (2 and 6) slideshows as well, or would that be different? I'm using [Stellar.js](http://markdalgleish.com/projects/stellar.js/) on my (portfolio page)[http://joshuaogle.com/portfolio], and while I seem to have a bug with the backgrounds lining up right if the images take a while to load, that should be easy to fix and the script was a snap to set up.

Actually I've already reused a few of the Middleman tricks from your site and I may be giving a talk at our local Ruby meetup about tips and tricks (there has been a lot of interest in Middleman lately). Probably a blog post coming too. I'm not sure we've done anything yet that would work as a spin-off Middleman plugin, but this slideshow functionality could definitely be a good one if we get it right. Great idea.

**Comment by andreweick** [comment]
Your portfolio looks awesome 

I left the title slideshow, but I should have changed it -- I don't want a slideshow at all anymore -- more just a good layout.  Stellar.js looks great, but I'm going for subtle parallax effect, so I think your page is a great start.  You probably say "that's straight HTML" and I think your right, I'm just struggling with relative image size and layout.

Why don't we start (simple?) with a template that I can put full width images into.  Image, text, Image, text

What do you think the markup would look like to make [this](https://www.storehouse.co/stories/s6cs-ice-worlds)? (I'm not tied to liquid or this layout -- more trying to get across what I am looking for to get your creativity pointed...)

{% Title "head" "subhead" url %} // parallax effect on title

{% Pull quote %}  // just noticed they added parallax effect on quote

Text text text

{% Full-bleed image %}

{% full-image %}

etc etc etc.

**Comment by andreweick** [comment]
Also, I'm still lost on "what size" images should be made to -- I know I have to make relative sizes (for the different devices / resolutions", but I think I'm struggling with "what size" -- could you make me a recipe that says "all images need to in boxes (2048x2048, 1024x1024, etc)

**Comment by joshuaogle** [comment]
Image sizes are definitely a concern here. We can make them stretch to cover, but of course larger resolutions to cover desktop screens are best. You want to be careful about making mobile screens download such a large image, so I usually do some sort of image compression for these. I can certainly work out some examples for you.

**Comment by andreweick** [comment]
Awesome -- I should have split this into another thread --

I can generate as many sizes as are needed (it's just an applescript I run over the files ) It's just getting the sizes and the retina and things!

**Comment by andreweick** [comment]
Any thoughts on this?  Is there something I can brainstorm with you?

**Comment by joshuaogle** [comment]
I was already halfway done with these updates, so I wanted to get them out before we brainstormed. I got the two big features, so we can build on it now.

Take a look at the PR, see where you may want parralax backgrounds (the cover title is the biggest one I think). And I think you were describing a full width image background with a quote over the top, but let me know if that's right.
